# NOTE: This file is auto-generated by @truveta/devkit.  Do not edit manually.

from urllib.parse import quote

from httpx import AsyncClient

from .types import (
    ExchangeRequest,
    ExchangeResponse,
    FinalizeSessionRequest,
    InitializeSessionResponse,
)


class OpenLinkTokenServiceClient:
    def __init__(self, base_url: str, client: AsyncClient) -> None:
        self._base_url = base_url
        self._client = client

    async def exchange_exchange(
        self, version: str, body: ExchangeRequest
    ) -> ExchangeResponse:
        url = f"{self._base_url}/v{quote(str(version))}/Exchange"
        response = await self._client.post(
            url,
            content=body.model_dump_json(by_alias=True),
            headers={"Content-Type": "application/json"},
        )
        response.raise_for_status()
        return ExchangeResponse.model_validate(response.json())

    async def upload_initialize_session(
        self, exchange_id: str, version: str
    ) -> InitializeSessionResponse:
        url = (
            f"{self._base_url}/v{quote(str(version))}/uploads/{quote(str(exchange_id))}"
        )
        response = await self._client.post(url)
        response.raise_for_status()
        return InitializeSessionResponse.model_validate(response.json())

    async def upload_upload_chunk(
        self,
        exchange_id: str,
        version: str,
        body: bytes,
        chunk_index: int,
        chunk_checksum: str,
    ) -> None:
        url = f"{self._base_url}/v{quote(str(version))}/uploads/{quote(str(exchange_id))}/chunks/{chunk_index}"
        response = await self._client.put(
            url,
            content=body,
            headers={
                "Content-Type": "application/octet-stream",
                "Chunk-Checksum": chunk_checksum,
            },
        )
        response.raise_for_status()

    async def upload_finalize_session(
        self, exchange_id: str, version: str, body: FinalizeSessionRequest
    ) -> None:
        url = f"{self._base_url}/v{quote(str(version))}/uploads/{quote(str(exchange_id))}/complete"
        response = await self._client.post(
            url,
            content=body.model_dump_json(by_alias=True),
            headers={"Content-Type": "application/json"},
        )
        response.raise_for_status()
